### ISSUE TITLE
Define API for "El Almirante"

### ISSUE THREAD

**Issue by antonioortizpola** [elalmirante/elalmirante#12]
I think it is necessary to implement an API to allow easy communication outside the server where is installed.
This could allow us to create external clients like web pages for easier management or remote control from CI/CD systems like Gitlab.
The API needs to be secure, since it looks that we are going with gRPC this could be handled with SSL/TLS, so this is a point, then also the  API it self needs to be defined, from the top of mi mind i think of this services:

- [ ] version: Return El Almirante version installed.
- [ ] query: Brings a list of servers, * by default.
- [ ] deploy: Deploy to servers based on a query
- [ ] addServer: Adds a server
- [ ] removeServer: Removes a server
- [ ] addServerTag: Adds a tag o a server
- [ ] removeServerTag: Removes a tag from a server
- [ ] updateServer: Change the name or description of the server

**Comment by ozkar99** [comment]
not so sure about adding CRUD operations, but the rest of the api proposal seems nice.

**Comment by antonioortizpola** [comment]
@ozkar99 If now, how are you planning to modify the actual state of the servers?

**Comment by ozkar99** [comment]
modify config.yml manually (like prometheus)

(or it could also be done via automating a ci/cd flow and just push to a repo with the config.yml file there)

**Comment by ozkar99** [comment]
on another note: `list` can be reduced to `query *` to get all servers.

**Comment by antonioortizpola** [comment]
@ozkar99 ls removed, you are right, it is not necessary

**Comment by antonioortizpola** [comment]
Closing for now since there is no necessary, will reopen if the problem came up again
